version: '3.8'

services:
  nutricontrol-pwa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Vite default dev port
    environment:
      - NODE_ENV=development
